### ISSUE TITLE
Keras with MxNet running only on CPU

### ISSUE THREAD

**Issue by mongoose54** [deep-learning-tools/keras#29]
@sandeep-krishnamurthy Great work! I have used Mxnet as backend for Keras 1.2 in your previous repository: https://github.com/dmlc/keras and I really loved it! Congratulations!

I came across your new forked repository for keras 2.x but I am having trouble to use the GPU. More specifically I followed the instructions from https://github.com/deep-learning-tools/keras/wiki/Installation-Guide---Keras-with-MXNet-backend and I installed the `mxnet-cu80` since I have CUDA 8. MxNet loads/works fine but when I try to run a Keras example: https://github.com/deep-learning-tools/keras/blob/master/examples/cifar10_cnn.py the experiment runs on the CPU and not the GPU. What am I doing wrong? Thanks

**Comment by sandeep-krishnamurthy** [comment]
Thanks for trying out Keras2 with MXNet backend. Let us know any issues you face.
We will soon create PR with keras-team.

For multi-gpu training, did you compile the model with context=[gpu_ids]?

Something like:

```
# Compile the model by specifying context with list of GPU IDs to be used during training.
gpu_list = ["gpu(0)", "gpu(1)", "gpu(2)", "gpu(3)"] 
model.compile(loss='categorical_crossentropy',
              optimizer=opt,
              metrics=['accuracy'], context=gpu_list)
```
Note: just take the "Context" thing from above sample code.

**Comment by mongoose54** [comment]
@sandeep-krishnamurthy  Thanks for the reply. Yes I am using the code above. Previously, when I installed Keras/MxNet per instructions here: https://github.com/dmlc/keras/wiki/Installation it worked fine but that doesn't support Keras 2.x .Correct? That's the reason I tried the new fork: https://github.com/deep-learning-tools/keras/wiki/Installation-Guide---Keras-with-MXNet-backend 

I might be doing something wrong.

**Comment by sandeep-krishnamurthy** [comment]
This PR - https://github.com/deep-learning-tools/keras/pull/31
should fix the bug.

**Comment by sandeep-krishnamurthy** [comment]
Code merged @mongoose54 - Let me know if latest do not work for you. 
I have tested and it should be working now.

**Comment by sandeep-krishnamurthy** [comment]
Resolving as it is tested.
